-- TaskForge AI ⚡ - Database Schema (PostgreSQL / Supabase)

-- 1. Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Table: User Progress (Gamification & Streaks)
CREATE TABLE IF NOT EXISTS public.user_progress (
    user_id UUID REFERENCES auth.users(id) PRIMARY KEY,
    name TEXT,
    xp INTEGER DEFAULT 0,
    streak INTEGER DEFAULT 0,
    dias_ativos TEXT[] DEFAULT '{}',
    badges JSONB DEFAULT '{}',
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: Tasks
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    titulo TEXT NOT NULL,
    status TEXT DEFAULT 'PENDENTE', -- 'PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO'
    xp_ganho INTEGER DEFAULT 10,
    primeiro_passo TEXT,
    iniciado_em TIMESTAMPTZ,
    concluido_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: Task Events (Audit/Analytics)
CREATE TABLE IF NOT EXISTS public.task_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL, -- 'created', 'started', 'completed', 'stuck'
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Row Level Security (RLS) - Crucial for Portfolio
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_events ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can see their own progress" 
ON public.user_progress FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own tasks" 
ON public.tasks FOR ALL 
USING (auth.uid() = user_id);

-- 6. RPC Function for Leaderboard (used in progress.js)
CREATE OR REPLACE FUNCTION get_leaderboard()
RETURNS TABLE (
    user_id UUID,
    name TEXT,
    xp INTEGER,
    streak INTEGER,
    posicao BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        up.user_id,
        up.name,
        up.xp,
        up.streak,
        ROW_NUMBER() OVER (ORDER BY up.xp DESC) as posicao
    FROM public.user_progress up
    LIMIT 100;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
